apiVersion: apps/v1
kind: Deployment
metadata:
  name: oeson-app
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oeson-app
  template:
    metadata:
      labels:
        app: oeson-app
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: oeson-container
          image: baffoe6/oeson-app:1.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
