apiVersion: v1
kind: Service
metadata:
  name: oeson-service
  namespace: microservices
spec:
  selector:
    app: oeson-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
